services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: streampeek
      POSTGRES_PASSWORD: streampeek
      POSTGRES_DB: streampeek
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: